"""initial schema

Revision ID: aa7c20024f53
Revises: 
Create Date: 2026-06-14 15:40:03.439556
"""
from alembic import op
import sqlalchemy as sa


revision = 'aa7c20024f53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_table('checks',
    sa.Column('check_id', sa.String(length=48), nullable=False),
    sa.Column('org', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('check_id')
    )
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checks_org'), ['org'], unique=False)

    op.create_table('contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org', sa.String(length=160), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_org'), ['org'], unique=False)

    op.create_table('credit_accounts',
    sa.Column('org', sa.String(length=160), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('org')
    )
    op.create_table('network_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('name_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_hash', 'name_hash', name='uq_identity_hash_name')
    )
    with op.batch_alter_table('network_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_identities_id_hash'), ['id_hash'], unique=False)

    op.create_table('network_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combo_hash', sa.String(length=64), nullable=False),
    sa.Column('org', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combo_hash', 'org', name='uq_report_combo_org')
    )
    with op.batch_alter_table('network_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_reports_combo_hash'), ['combo_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_reports_combo_hash'))

    op.drop_table('network_reports')
    with op.batch_alter_table('network_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_identities_id_hash'))

    op.drop_table('network_identities')
    op.drop_table('credit_accounts')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_org'))

    op.drop_table('contributions')
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checks_org'))

    op.drop_table('checks')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
